[package]
    edition="2021"
    name   ="maldon"
    version="0.2.1"

[dependencies]
    alloy-primitives="0.7"
    clap            ={version="4.5", features=["derive"]}
    hex             ="0.4"
    rand            ="0.8"
    rayon           ="1.10"
    thiserror       ="1"
